name: extension_service
description: "This package contains a set  of useful extension methods for common types in Flutter Dart. These extensions enhance the functionality of standard classes, providing convenient methods for everyday tasks."
version: 0.0.2
homepage: https://github.com/Saw2110/extension_service.git

plugin: 
  platforms:
    android:
    ios:
    linux:
    macos:
    web:
    windows:

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:

